#!/bin/bash

function ensureTransmissionIsNotRunning {
	sleep 5
	process=$(pgrep -a transmission)
	
	if [ -n "$process" ]; then
		echo "WARNING: It seems like transmission is still running. Was down.sh really run?"
		echo "$process"
		cmd="sudo /usr/local/bin/torrent stop"
		$cmd
	fi
}

case "$1" in
	start)
		echo "Starting openvpn anonine service..."
		cmd="sudo /etc/init.d/openvpn start anonine"
		$cmd
		;;
	stop)
		echo "Stopping openvpn anonine service..."
		cmd="sudo /etc/init.d/openvpn stop"
		$cmd
		ensureTransmissionIsNotRunning
		;;
	*)
		echo "Invalid parameter"
		exit 2
		;;
esac
log=/var/log/openvpn.log
sleep 1
echo "tail $log:"
tail -n 50 $log | grep "$(date +%H:%M)"
exit 0
