#!/usr/bin/python

import os
import subprocess
from prettytable import PrettyTable

MOVIESDIR = "/data/media/movies"
SERIESDIR = "/data/media/series"

class MediaDir:
    def __init__(self, path):
        self.path = path
    def get_name(self):
        return os.path.basename(self.path)
    def get_size(self):
        return subprocess.check_output(["du", "-sh", self.path], universal_newlines=True).split()[0]
    def get_num_files(self):
        num_files = 0
        for current_dir, sub_dirs, files in os.walk(self.path):
            for filename in files:
                if not (filename.endswith(".srt") or filename.endswith(".sub")):
                    num_files += 1
        return str(num_files)

def get_directories(path):
    current_dir, dirs, files = next(os.walk(path))
    return sorted(dirs)

def movie_summary():
    print("+-------------------------------------+")
    print("|            MOVIE SUMMARY            |")

    table = PrettyTable(["Genre", "Movies", "Size"])
    table.align["Genre"] = "l"
    table.align["Movies"] = "r"
    table.align["Size"] = "r"
 
    for directory in get_directories(MOVIESDIR):
        genre_dir = MediaDir(MOVIESDIR + "/" + directory)
        table.add_row([genre_dir.get_name(), genre_dir.get_num_files(), genre_dir.get_size()])

    movies_dir = MediaDir(MOVIESDIR)
    table.add_row(["==================", "======", "====="])
    table.add_row(["TOTAL", movies_dir.get_num_files(), movies_dir.get_size()])

    print(table)

def series_summary():
    print("+-------------------------------------+")
    print("|           SERIES SUMMARY            |")

    table = PrettyTable(["Data", "Value"])
    table.align["Data"] = "l"
    table.align["Value"] = "r"
    
    series_dir = MediaDir(SERIESDIR)
    table.add_row(["Number of series", len(get_directories(series_dir.path))])
    table.add_row(["Number of episodes         ", series_dir.get_num_files()])
    table.add_row(["Total size", series_dir.get_size()])

    print(table)

movie_summary()
series_summary()
